### ISSUE TITLE
Can not runing in MacOs-10.14.5

### ISSUE THREAD

**Issue by lescpsn** [double2kill/vscode-auto-encrypt#1]
1. mkdir AutoEncryptTest

2. cd AutoEncryptTest; vim  .encryptrc
   # cat .encryptrc
      a.sh

3. edit a.sh

4. save a.sh can not encrypt

**Comment by double2kill** [comment]
Thank you for telling me bug in MacOs, I didn't have a try in MacOs, I'll look this issue these days and sorry for reply late.

**Comment by double2kill** [comment]
@lescpsn, I just published the new version-v0.0.4, please try it when you are convenient.

**Comment by UtsavChokshiCNU** [comment]
@double2kill ..
It is not working on `macOS mojave`.

If you need a quick tester, I can help you out.

**Comment by double2kill** [comment]
@UtsavChokshiCNU , I test `macOS mojave 10.14.6`, it is working. I have no idea where I can see your extension log. can you debug the extension?
```
git clone 
npm install
npm run compile
Press F5 and test
```
