### ISSUE TITLE
Issues on Mac OS

### ISSUE THREAD

**Issue by UtsavChokshiCNU** [double2kill/vscode-auto-encrypt#2]
Hello,
I am facing few issues while using your extension on MacOS.

OS details : 
```
MacOS Mojave Version 10.14.6
```
VSCode details : 
```
Version: 1.45.0
Commit: d69a79b73808559a91206d73d7717ff5f798f23c
Date: 2020-05-07T15:57:33.467Z (1 day ago)
Electron: 7.2.4
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Darwin x64 18.7.0
```

Issue 1 :
```
When I create  `.encryptrc`, it encrypts itself and creates : `encryptrc.encrypt` with its content.
It happens in both cases : 
1.  When file name I specify (e.g. `password.txt`) is not present.
2. When file name I specify is present.
```

Issue 2 : 
```
How do I specify multiple filenames in `.encryptrc`.
I tried to separate file names by space as well as a newline.  But it always processes only the first file.
e.g. 
`password1.txt password2.txt`
```

Issue 3:
```
When I specify filepath (i.e. file not located on root of project) (e.g. t1/t11.txt) then
1. It creates encrypted file at root. So file `t11.txt.encrypt` is created at root.
2. It does not create/open decrypted file on opening `t11.txt.encrypt`.
```

Issue 4:
```
When `.encryptrc` is empty, it starts encrypting all files in `.vscode`
```

**Comment by double2kill** [comment]
Good catch, let me investigate it.

**Comment by double2kill** [comment]
@UtsavChokshiCNU  I believe issue 1 is the same with issue 4, the behavior come from empty `.encryptrc` file. there are two steps, first, create an empty `.encryptrc`, then, the file is modified.
I will fix issue 2/3/4. Thank you for finding these bugs.

**Comment by UtsavChokshiCNU** [comment]
Thanks for your active support.
I can test it out early release on weekend.

**Comment by UtsavChokshiCNU** [comment]
I'll also test it out on Remote Containers.
It should work, right?

**Comment by double2kill** [comment]
Please test the new version - 0.0.5. I updated it just now.

**Comment by double2kill** [comment]
For issue2, you can specify multiple filenames by \n. and you can use *

.encryptrc multiple filenames example
```
a.js
password.js
*.md
```

**Comment by double2kill** [comment]
I'd like close the issue now, If you still find problems, please let me know

**Comment by UtsavChokshiCNU** [comment]
@double2kill .. Thanks for resolving. It works for me now.
